package com.jstuart0.personaldiary.data.local.entity

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index

/**
 * Many-to-many relationship between entries and tags
 */
@Entity(
    tableName = "entry_tags",
    primaryKeys = ["entryId", "tagName"],
    foreignKeys = [
        ForeignKey(
            entity = EntryEntity::class,
            parentColumns = ["entryId"],
            childColumns = ["entryId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [Index("entryId"), Index("tagName")]
)
data class EntryTagEntity(
    val entryId: String,
    val tagName: String,
    val autoGenerated: Boolean = false
)
