//
//  Tag.swift
//  PersonalDiary
//
//  Created by Claude Code on 2025-10-31.
//  Copyright © 2025 Personal Diary Platform. All rights reserved.
//

import Foundation

/// Tag model
struct Tag: Identifiable, Codable, Hashable {
    let id: String
    let name: String
    let isAutoGenerated: Bool

    enum CodingKeys: String, CodingKey {
        case id
        case name
        case isAutoGenerated = "is_auto_generated"
    }

    init(id: String = UUID().uuidString, name: String, isAutoGenerated: Bool = false) {
        self.id = id
        self.name = name
        self.isAutoGenerated = isAutoGenerated
    }

    /// Computed property for display
    var displayName: String {
        name
    }

    /// Check if tag is a system tag
    var isSystemTag: Bool {
        name.hasPrefix("source:") || name.hasPrefix("shared:")
    }

    /// Get tag color based on type
    var color: String {
        if isSystemTag {
            return "gray"
        } else if isAutoGenerated {
            return "blue"
        } else {
            return "purple"
        }
    }

    /// Get tag icon
    var icon: String? {
        if name.hasPrefix("source:facebook") {
            return "f.circle.fill"
        } else if name.hasPrefix("source:instagram") {
            return "camera.circle.fill"
        } else if name.hasPrefix("shared:") {
            return "square.and.arrow.up.fill"
        }
        return nil
    }
}

/// Tag suggestion response
struct TagSuggestion: Codable {
    let name: String
    let confidence: Double
    let reason: String?
}

/// Popular tags response
struct PopularTagsResponse: Codable {
    let tags: [String]
    let period: String
}
